version: '3.5'

services:
  pp-api:
    build:
      context: .
      dockerfile: Dockerfile.Api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      MongoDb: "mongodb://developer:developerccc1345@newry-nonprod-new.cluster-cnowxsoknapu.ap-southeast-1.docdb.amazonaws.com:27017/pp-app?replicaSet=rs0&readPreference=primaryPreferred&retryWrites=false"
      RedisConfig": "newry-els-cache-new-dev.ung9tx.clustercfg.apse1.cache.amazonaws.com:6379"
      RedisService": "pp-app"
      JwtIssuer": "http://127.0.0.1:8080/"
      JwtAudience": "http://127.0.0.1:8080/"
      JwtKey": "sadasdasd54as45das544d6as4d64asd648354f56hfh56k465iu4654g564sf56g4ds65g4sd65g4654tw56s"